# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_auto_20180618_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-date_uploaded']},
        ),
    ]
